image_list: |
  registry.aliyuncs.com/google_containers/kube-apiserver:v1.34.4
  registry.aliyuncs.com/google_containers/kube-controller-manager:v1.34.4
  registry.aliyuncs.com/google_containers/kube-scheduler:v1.34.4
  registry.aliyuncs.com/google_containers/kube-proxy:v1.34.4
  registry.aliyuncs.com/google_containers/coredns:v1.12.1
  registry.aliyuncs.com/google_containers/pause:3.10.1
  registry.aliyuncs.com/google_containers/etcd:3.6.5-0
  docker.io/kubeovn/kube-ovn:v1.15.2
  docker.io/kubeovn/vpc-nat-gateway:v1.15.2
  ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot-thick
  registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.35.0
  docker.io/projecthami/hami:v2.7.1
  docker.io/jettech/kube-webhook-certgen:v1.5.2
  docker.io/liangjw/kube-webhook-certgen:v1.1.1
  docker.io/projecthami/hami-webui-fe-oss:v1.0.5
  docker.io/projecthami/hami-webui-be-oss:v1.0.5
  nvcr.io/nvidia/k8s/dcgm-exporter:3.3.7-3.5.0-ubuntu22.04